name = "Pszygoda Nagrywanie"
author = "FFTV"
version = "1.0.0-nagrywanie.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index-portals-1.0.0.toml"
hash-format = "sha256"
hash = "a3acd7254cc0df70711bde7354249e918c059feb1ebcba4060b5f0b51d6644a8"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
