name = "Pszygoda Portale"
author = "FFTV"
version = "1.0.0-portals.34"
pack-format = "packwiz:1.1.0"

[index]
file = "index-portals-1.0.0.toml"
hash-format = "sha256"
hash = "c28cf4845c3714803cc7c1dcdddd91d8eecd1c3b962c99f44da83f1bd2e4daba"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
