[CmdletBinding()]
param(
    [string] $SourceDirectory,
    [string] $OutputPath
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$repositoryRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
if (-not $SourceDirectory) {
    $SourceDirectory = Join-Path $repositoryRoot '_shader-src\Photon-Pszygoda-1.4'
}
if (-not $OutputPath) {
    $OutputPath = Join-Path $repositoryRoot 'shaderpacks\Photon-Pszygoda-1.4.zip'
}

$sourceRoot = (Resolve-Path -LiteralPath $SourceDirectory).Path
$outputFile = [System.IO.Path]::GetFullPath($OutputPath)
$world0Source = Join-Path $sourceRoot 'shaders\world0'
$dimensionMap = Join-Path $sourceRoot 'shaders\dimension.properties'
$cloudVertexProgram = Join-Path $sourceRoot 'shaders\program\gbuffers_clouds.vsh'
$cloudFragmentProgram = Join-Path $sourceRoot 'shaders\program\gbuffers_clouds.fsh'
$cloudVertexWrapper = Join-Path $world0Source 'gbuffers_clouds.vsh'
$cloudFragmentWrapper = Join-Path $world0Source 'gbuffers_clouds.fsh'
if (-not (Test-Path -LiteralPath $world0Source -PathType Container)) {
    throw "Missing source wrapper directory: $world0Source"
}
if (-not (Test-Path -LiteralPath $dimensionMap -PathType Leaf)) {
    throw "Missing Iris dimension map: $dimensionMap"
}
$shaderProperties = Join-Path $sourceRoot 'shaders\shaders.properties'
if (-not (Select-String -LiteralPath $shaderProperties -SimpleMatch 'blend.gbuffers_clouds.colortex13' -Quiet)) {
    throw 'Dedicated vanilla-cloud pass must use the premultiplied-alpha colortex13 blend.'
}
foreach ($cloudFile in @(
    $cloudVertexProgram,
    $cloudFragmentProgram,
    $cloudVertexWrapper,
    $cloudFragmentWrapper
)) {
    if (-not (Test-Path -LiteralPath $cloudFile -PathType Leaf)) {
        throw "Missing dedicated vanilla-cloud shader pass: $cloudFile"
    }
}
if (Test-Path -LiteralPath (Join-Path $sourceRoot 'shaders\worldKrawedz')) {
    throw 'worldKrawedz must be generated by this script, not committed in shader source.'
}

$systemTemp = [System.IO.Path]::GetFullPath([System.IO.Path]::GetTempPath())
$workRoot = [System.IO.Path]::GetFullPath((Join-Path $systemTemp ("pszygoda-photon-{0}" -f [guid]::NewGuid().ToString('N'))))
if (-not $workRoot.StartsWith($systemTemp, [System.StringComparison]::OrdinalIgnoreCase) -or
    -not ([System.IO.Path]::GetFileName($workRoot)).StartsWith('pszygoda-photon-', [System.StringComparison]::Ordinal)) {
    throw "Refusing unsafe temporary path: $workRoot"
}

$stageRoot = Join-Path $workRoot 'stage'
$temporaryZip = Join-Path $workRoot 'Photon-Pszygoda-1.4.zip'
$utf8NoBom = [System.Text.UTF8Encoding]::new($false)

try {
    New-Item -ItemType Directory -Path $stageRoot -Force | Out-Null
    Copy-Item -Path (Join-Path $sourceRoot '*') -Destination $stageRoot -Recurse -Force

    $world0Stage = Join-Path $stageRoot 'shaders\world0'
    $worldKrawedzStage = Join-Path $stageRoot 'shaders\worldKrawedz'
    Copy-Item -LiteralPath $world0Stage -Destination $worldKrawedzStage -Recurse -Force

    $wrapperExtensions = [System.Collections.Generic.HashSet[string]]::new(
        [System.StringComparer]::OrdinalIgnoreCase
    )
    foreach ($extension in @('.fsh', '.vsh', '.csh', '.glsl')) {
        [void] $wrapperExtensions.Add($extension)
    }

    Get-ChildItem -LiteralPath $worldKrawedzStage -File -Recurse | ForEach-Object {
        if (-not $wrapperExtensions.Contains($_.Extension)) {
            return
        }

        $text = [System.IO.File]::ReadAllText($_.FullName)
        $newline = if ($text.Contains("`r`n")) { "`r`n" } else { "`n" }
        if ($text.StartsWith('#version', [System.StringComparison]::Ordinal)) {
            $lineEnd = $text.IndexOf($newline, [System.StringComparison]::Ordinal)
            if ($lineEnd -lt 0) {
                $text = $text + $newline + '#define WORLD_KRAWEDZ' + $newline
            } else {
                $insertAt = $lineEnd + $newline.Length
                $text = $text.Insert($insertAt, '#define WORLD_KRAWEDZ' + $newline)
            }
        } else {
            $text = '#define WORLD_KRAWEDZ' + $newline + $text
        }
        [System.IO.File]::WriteAllText($_.FullName, $text, $utf8NoBom)
    }

    # Iris does not inherit program.<directory> conditions when a new wrapper
    # directory is introduced. Every world0 toggle must therefore have an
    # identical worldKrawedz counterpart, including conditional duplicates.
    $stagedProperties = Join-Path $stageRoot 'shaders\shaders.properties'
    $propertyLines = [System.IO.File]::ReadAllLines($stagedProperties)
    $world0Rules = [System.Collections.Generic.List[string]]::new()
    $worldKrawedzRules = [System.Collections.Generic.List[string]]::new()
    $conditionStack = [System.Collections.Generic.List[object]]::new()
    foreach ($line in $propertyLines) {
        $trimmed = $line.Trim()
        if ($trimmed -match '^#(if|ifdef|ifndef)\b') {
            $conditionStack.Add([pscustomobject]@{ Open = $trimmed; Branch = $trimmed })
            continue
        }
        if ($trimmed -match '^#(elif|else)\b') {
            if ($conditionStack.Count -eq 0) {
                throw "Unbalanced shader preprocessor branch: $trimmed"
            }
            $conditionStack[$conditionStack.Count - 1].Branch = $trimmed
            continue
        }
        if ($trimmed -match '^#endif\b') {
            if ($conditionStack.Count -eq 0) {
                throw 'Unbalanced shader preprocessor #endif.'
            }
            $conditionStack.RemoveAt($conditionStack.Count - 1)
            continue
        }
        if ($line -match '^\s*program\.(?<world>world0|worldKrawedz)/(?<program>[^=\s]+)\s*=\s*(?<value>\S+)\s*$') {
            $context = @($conditionStack | ForEach-Object {
                '{0}|{1}' -f $_.Open, $_.Branch
            }) -join ' > '
            $signature = '{0}={1} @ {2}' -f $Matches.program, $Matches.value, $context
            if ($Matches.world -eq 'world0') {
                $world0Rules.Add($signature)
            } else {
                $worldKrawedzRules.Add($signature)
            }
        }
    }
    if ($conditionStack.Count -ne 0) {
        throw 'Unbalanced shader preprocessor conditions at end of shaders.properties.'
    }
    if ($world0Rules.Count -ne $worldKrawedzRules.Count) {
        throw "worldKrawedz program toggle count differs from world0: $($worldKrawedzRules.Count)/$($world0Rules.Count)"
    }
    for ($index = 0; $index -lt $world0Rules.Count; $index++) {
        if ($world0Rules[$index] -ne $worldKrawedzRules[$index]) {
            throw "worldKrawedz program toggle $index differs from world0:`nworld0: $($world0Rules[$index])`nworldKrawedz: $($worldKrawedzRules[$index])"
        }
    }

    Add-Type -AssemblyName System.IO.Compression
    $fixedTimestamp = [DateTimeOffset]::new(2000, 1, 1, 0, 0, 0, [TimeSpan]::Zero)
    $files = Get-ChildItem -LiteralPath $stageRoot -File -Recurse | Sort-Object {
        $_.FullName.Substring($stageRoot.Length + 1).Replace('\', '/')
    }

    $zipStream = [System.IO.File]::Open(
        $temporaryZip,
        [System.IO.FileMode]::CreateNew,
        [System.IO.FileAccess]::ReadWrite,
        [System.IO.FileShare]::None
    )
    try {
        $archive = [System.IO.Compression.ZipArchive]::new(
            $zipStream,
            [System.IO.Compression.ZipArchiveMode]::Create,
            $true
        )
        try {
            foreach ($file in $files) {
                $relativePath = $file.FullName.Substring($stageRoot.Length + 1).Replace('\', '/')
                $entry = $archive.CreateEntry(
                    $relativePath,
                    [System.IO.Compression.CompressionLevel]::Optimal
                )
                $entry.LastWriteTime = $fixedTimestamp
                $input = [System.IO.File]::OpenRead($file.FullName)
                $output = $entry.Open()
                try {
                    $input.CopyTo($output)
                } finally {
                    $output.Dispose()
                    $input.Dispose()
                }
            }
        } finally {
            $archive.Dispose()
        }
    } finally {
        $zipStream.Dispose()
    }

    $outputDirectory = [System.IO.Path]::GetDirectoryName($outputFile)
    New-Item -ItemType Directory -Path $outputDirectory -Force | Out-Null
    [System.IO.File]::Move($temporaryZip, $outputFile, $true)

    $hash = (Get-FileHash -LiteralPath $outputFile -Algorithm SHA256).Hash.ToLowerInvariant()
    $worldKrawedzFiles = (Get-ChildItem -LiteralPath $worldKrawedzStage -File -Recurse).Count
    Write-Output "Built $outputFile"
    Write-Output "worldKrawedz wrappers: $worldKrawedzFiles"
    Write-Output "SHA-256: $hash"
} finally {
    if (Test-Path -LiteralPath $workRoot) {
        $resolvedWorkRoot = [System.IO.Path]::GetFullPath($workRoot)
        if (-not $resolvedWorkRoot.StartsWith($systemTemp, [System.StringComparison]::OrdinalIgnoreCase) -or
            -not ([System.IO.Path]::GetFileName($resolvedWorkRoot)).StartsWith('pszygoda-photon-', [System.StringComparison]::Ordinal)) {
            throw "Refusing unsafe cleanup path: $resolvedWorkRoot"
        }
        Remove-Item -LiteralPath $resolvedWorkRoot -Recurse -Force
    }
}
